// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl5lhCv9lJxWHmz7dzSzosCgHt79IngIk',
    appId: '1:130873886454:web:928fcfb182897063c18ed7',
    messagingSenderId: '130873886454',
    projectId: 'platzitripsapp-8af20',
    authDomain: 'platzitripsapp-8af20.firebaseapp.com',
    storageBucket: 'platzitripsapp-8af20.appspot.com',
    measurementId: 'G-F2R3D6QY0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUVBSjTi4qyF2axAtfckEBd5Rb5RilpUU',
    appId: '1:130873886454:android:5551e8be2aaea55ac18ed7',
    messagingSenderId: '130873886454',
    projectId: 'platzitripsapp-8af20',
    storageBucket: 'platzitripsapp-8af20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF6fLCzGiWGJcVMwiMTdSzj1d0SKB37fw',
    appId: '1:130873886454:ios:60a5e199bfd87de7c18ed7',
    messagingSenderId: '130873886454',
    projectId: 'platzitripsapp-8af20',
    storageBucket: 'platzitripsapp-8af20.appspot.com',
    iosClientId: '130873886454-aojcsf4hmlof4s5uq0mhtqrv6lrp0agr.apps.googleusercontent.com',
    iosBundleId: 'com.example.platziTripsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF6fLCzGiWGJcVMwiMTdSzj1d0SKB37fw',
    appId: '1:130873886454:ios:60a5e199bfd87de7c18ed7',
    messagingSenderId: '130873886454',
    projectId: 'platzitripsapp-8af20',
    storageBucket: 'platzitripsapp-8af20.appspot.com',
    iosClientId: '130873886454-aojcsf4hmlof4s5uq0mhtqrv6lrp0agr.apps.googleusercontent.com',
    iosBundleId: 'com.example.platziTripsApp',
  );
}
